pub mod agent_catalog;
pub mod agent_runner;
pub mod anthropic;
pub mod config;
pub mod extraction;
pub mod narrator;
pub mod pg;
pub mod planner;
pub mod pr_engine;
pub mod routes;
pub mod session;
pub mod state;
pub mod tools;
pub mod work_queue;

#[cfg(feature = "slack")]
pub mod slack;
#[cfg(feature = "slack")]
pub mod slack_messages;
#[cfg(feature = "slack")]
pub mod slack_notifier;
#[cfg(feature = "slack")]
pub mod slack_routes;
